### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [Shardcached/libshardcache#5]
I would like to point out that identifiers like "[`__arc`](https://github.com/Shardcached/libshardcache/blob/94b960c48bcf2e1ae79b6f43ab99b428ebae2752/src/arc.h#L13)" and "[`__SHARDCACHE_H__`](https://github.com/Shardcached/libshardcache/blob/2b80330ff8b31630178cd4bff8e5112190510bae/src/shardcache.h#L1)" [do eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by biappi** [comment]
Hi Markus,

In order to avoid endless streams of statements-as-questions in the other dependency, can i ask you to *clearly state* your complete set of requirements?

i gather you're after
- naming scheme
- c++ inclusion compatibility
- non-trivial build environment (autotools or cmake, possibly even with some restrictions on versions)

i also gather it's difficult to you to contribute directly to the project, is that right?

since you worked on libhl and now you're approaching libshardcache i gather those requirements will hold true for the shardcached project as well?

**Comment by elfring** [comment]
The library for a "shard cache" contains also some update candidates which are similar to other C software issues like in "libhl".
How would you like to improve the affected source files for this area here?

**Comment by xant** [comment]
I think it's not going to be high priority here ... some easy and quick fixes can probably be applied sooner

**Comment by xant** [comment]
7635e6843869c4e1f0755e3fb021b96d0237e29c

**Comment by elfring** [comment]
Thanks for [your source code improvement](https://github.com/Shardcached/libshardcache/commit/7635e6843869c4e1f0755e3fb021b96d0237e29c "Don't use names in the reserved namespace").
